# Claim db storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-observer-db
  labels:
    app.kubernetes.io/name: test-observer-db
    app.kubernetes.io/part-of: test-observer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Expose db to other pods
apiVersion: v1
kind: Service
metadata:
  name: test-observer-db
  labels:
    app.kubernetes.io/name: test-observer-db
    app.kubernetes.io/part-of: test-observer
spec:
  ports:
    - port: 5432
  selector:
    app.kubernetes.io/name: test-observer-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-observer-db
  labels:
    app.kubernetes.io/name: test-observer-db
    app.kubernetes.io/part-of: test-observer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-observer-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-observer-db
        app.kubernetes.io/part-of: test-observer
    spec:
      volumes:
        - name: test-observer-db
          persistentVolumeClaim:
            claimName: test-observer-db
      containers:
        - name: test-observer-db
          image: postgres:15.2
          volumeMounts:
            - name: test-observer-db
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
