# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas
    - prefer_relative_imports
    - prefer_final_locals
