header:
  - paths:
      - "backend/**/*.py"
    license:
      spdx-id: AGPL-3.0-only
      copyright-owner: Canonical Ltd.
      copyright-year: 2023
      software-name: Test Observer Backend
    paths-ignore:
      - "backend/charm/**"
  - paths:
      - "frontend/**/*.dart"
    license:
      spdx-id: GPL-3.0-only
      copyright-owner: Canonical Ltd.
      copyright-year: 2023
      software-name: Test Observer Frontend
      content: |
        Copyright (C) [year] [owner]

        This file is part of [software-name].

        [software-name] is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License version 3, as
        published by the Free Software Foundation.

        [software-name] is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program.  If not, see <https://www.gnu.org/licenses/>.
    language:
      Dart:
        extensions:
          - ".dart"
        comment_style_id: DoubleSlash
