FROM python:3.10

EXPOSE 30000

WORKDIR /home/app

COPY backend/poetry.lock .

COPY backend/pyproject.toml .

RUN pip3 install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --without dev

COPY ./backend .

CMD [ "uvicorn",  "test_observer.main:app", "--host", "0.0.0.0", "--port", "30000" ]
