# Copyright 2026 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-FileCopyrightText: Copyright 2026 Canonical Ltd.
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  SRC_PATH: "{{.ROOT_DIR}}/src"
  TESTS_PATH: "{{.ROOT_DIR}}/tests"
  ALL_PATH: "{{.ROOT_DIR}}/src {{.ROOT_DIR}}/tests"

env:
  PYTHONPATH: "{{.ROOT_DIR}}/lib:{{.ROOT_DIR}}/src"
  PYTHONBREAKPOINT: "pdb.set_trace"
  PY_COLORS: "1"

tasks:
  default:
    desc: Run format, lint and unit tasks
    cmds:
      - task: format
      - task: lint
      - task: unit-test

  format:
    desc: Apply coding style standards to code
    cmds:
      - uv run --group lint ruff format {{.ALL_PATH}}
      - uv run --group lint ruff check --fix {{.ALL_PATH}}

  lint:
    desc: Check code against coding style standards, and static checks
    cmds:
      - uv run --group lint --group unit --group integration codespell {{.ROOT_DIR}}
      - uv run --group lint --group unit --group integration ruff check {{.ALL_PATH}}
      - uv run --group lint --group unit --group integration ruff format --check --diff {{.ALL_PATH}}
      - uv run --group lint --group unit --group integration pyright {{.CLI_ARGS}}

  unit-test:
    desc: Run unit tests
    cmds:
      - >-
        uv run --group unit
        coverage run --source={{.SRC_PATH}} -m pytest
        -v
        -s
        --tb native
        {{.TESTS_PATH}}/unit
        {{.CLI_ARGS}}
      - uv run --group unit coverage report

  integration-test:
    desc: Run integration tests
    # The integration tests don't pack the charm. If CHARM_PATH is set, the tests deploy the
    # specified .charm file. Otherwise, the tests look for a .charm file in the project dir.
    cmds:
      - >-
        uv run --group integration
        pytest
        -v
        -s
        --tb native
        --log-cli-level=INFO
        {{.TESTS_PATH}}/integration
        {{.CLI_ARGS}}

