{
 "title": "Product & Artifact Deep Dive",
 "tags": [
  "product",
  "deep-dive"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "family",
    "label": "Product Family",
    "query": "label_values(test_observer_test_results, family)"
   },
   {
    "name": "artefact",
    "label": "Artefact Name",
    "query": "label_values(test_observer_test_results{family=~\"$family\"}, artefact_name)"
   },
   {
    "name": "stage",
    "label": "Stage",
    "query": "label_values(test_observer_test_results{artefact_name=~\"$artefact\"}, artefact_stage)"
   },
   {
    "name": "track",
    "label": "Track",
    "query": "label_values(test_observer_test_results{artefact_name=~\"$artefact\"}, track)"
   },
   { "name": "DS_PROMETHEUS", "label": "Prometheus Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (test_observer_test_results{artefact_name=~\"$artefact\", track=~\"$track\", artefact_stage=~\"$stage\", family=~\"$family\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Failures by Environment",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (environment_name) (test_observer_test_results{status=\"FAILED\", artefact_name=~\"$artefact\", track=~\"$track\", family=~\"$family\"})",
     "legendFormat": "{{environment_name}}"
    }
   ]
  },
  {
   "title": "Failing Test Plans",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (test_plan) (test_observer_test_results{status=\"FAILED\", artefact_name=~\"$artefact\", track=~\"$track\", family=~\"$family\"})"
    }
   ]
  },
  {
   "title": "Top Failing Individual Tests",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by (test_name) (test_observer_test_results{status=\"FAILED\", artefact_name=~\"$artefact\", track=~\"$track\", family=~\"$family\"}))",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Top 25 failing Interfaces",
   "type": "barchart",
   "description": "Note: Only works with the Charm family",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "topk(25, sum by (Interface) (label_replace(test_observer_test_results{status=\"FAILED\", artefact_name=~\"$artefact\", track=~\"$track\", family=~\"$family\"}, \"Interface\", \"$1\", \"test_plan\", \"[^/]+/[^/]+/([^/]+)/.*\")))"
    }
   ]
  },
  {
   "title": "Top Failing Artefacts",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "topk(10, sum by (artefact_name) (test_observer_test_results{status=\"FAILED\", family=~\"$family\", track=~\"$track\", artefact_stage=~\"$stage\"}))"
    }
   ]
  }
 ]
}