from enum import Enum

PREVIOUS_TEST_RESULT_COUNT = 10


class APIErrors(str, Enum):
    ARTEFACT_APPROVAL_REQUIRES_ALL_TESTEXECUTION_APPROVED = (
        "ARTEFACT_APPROVAL_REQUIRES_ALL_TESTEXECUTION_APPROVED"
    )
    ARTEFACT_REJECTION_REQUIRES_ONE_TESTEXECUTION_REJECTION = (
        "ARTEFACT_REJECTION_REQUIRES_ONE_TESTEXECUTION_REJECTION"
    )
