# Copyright (C) 2023 Canonical Ltd.
#
# This file is part of Test Observer Backend.
#
# Test Observer Backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3, as
# published by the Free Software Foundation.
#
# Test Observer Backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add index to test_execution_id in relevant links

Revision ID: ed261bbdb05d
Revises: 87f9e68e61a7
Create Date: 2025-06-04 12:02:02.316966+00:00

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = 'ed261bbdb05d'
down_revision = '87f9e68e61a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'test_execution_relevant_link_id_ix', 
        table_name='test_execution_relevant_link')
    op.create_index(
        op.f('test_execution_relevant_link_test_execution_id_ix'), 
        'test_execution_relevant_link', 
        ['test_execution_id'], 
        unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('test_execution_relevant_link_test_execution_id_ix'), 
        table_name='test_execution_relevant_link')
    op.create_index(
        'test_execution_relevant_link_id_ix', 
        'test_execution_relevant_link', 
        ['id'], 
        unique=False)
    # ### end Alembic commands ###
