"""Add archived field to Artefact model

Revision ID: 6a726050c944
Revises: 2be627e68efd
Create Date: 2025-04-01 18:04:50.835900+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a726050c944'
down_revision = '2be627e68efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artefact', sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.text("FALSE")))
    op.create_index(op.f('artefact_archived_ix'), 'artefact', ['archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('artefact_archived_ix'), table_name='artefact')
    op.drop_column('artefact', 'archived')
    # ### end Alembic commands ###
