# Copyright (C) 2023 Canonical Ltd.
#
# This file is part of Test Observer Backend.
#
# Test Observer Backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3, as
# published by the Free Software Foundation.
#
# Test Observer Backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add source specific issue statuses

Revision ID: 741fccc4d488
Revises: 3f6a99085db7
Create Date: 2025-12-01 12:13:19.286166+00:00

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "741fccc4d488"
down_revision = "3f6a99085db7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add GitHub statuses
    op.execute("ALTER TYPE issuestatus ADD VALUE 'GITHUB_OPEN'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'GITHUB_CLOSED'")

    # Add Jira statuses
    op.execute("ALTER TYPE issuestatus ADD VALUE 'JIRA_NEW'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'JIRA_INDETERMINATE'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'JIRA_DONE'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'JIRA_REJECTED'")

    # Add Launchpad statuses
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_NEW'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_INCOMPLETE'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_TRIAGED'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_IN_PROGRESS'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_CONFIRMED'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_FIX_RELEASED'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_INVALID'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_WONT_FIX'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_EXPIRED'")
    op.execute("ALTER TYPE issuestatus ADD VALUE 'LP_OPINION'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
