# Copyright (C) 2023 Canonical Ltd.
#
# This file is part of Test Observer Backend.
#
# Test Observer Backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3, as
# published by the Free Software Foundation.
#
# Test Observer Backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add reviewer pools

Revision ID: 89c6d33df8e1
Revises: 3f6a99085db7
Create Date: 2025-11-20 14:56:16.026301+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89c6d33df8e1'
down_revision = '3f6a99085db7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_pool',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('families', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('reviewer_pool_pkey')),
    sa.UniqueConstraint('name', name=op.f('reviewer_pool_name_key'))
    )
    op.create_table('pool_members',
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['reviewer_pool.id'], name=op.f('pool_members_pool_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('pool_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool_id', 'user_id', name=op.f('pool_members_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pool_members')
    op.drop_table('reviewer_pool')
    # ### end Alembic commands ###
