"""add test_execution_relevant_links

Revision ID: 87f9e68e61a7
Revises: b582856bd72e
Create Date: 2025-05-29 10:31:17.328173+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87f9e68e61a7"
down_revision = "b582856bd72e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_execution_relevant_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_execution_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_execution_id"],
            ["test_execution.id"],
            name=op.f("test_execution_relevant_link_test_execution_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("test_execution_relevant_link_pkey")),
    )
    op.create_index(
        op.f("test_execution_relevant_link_id_ix"),
        "test_execution_relevant_link",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("test_execution_relevant_link_id_ix"),
        table_name="test_execution_relevant_link",
    )
    op.drop_table("test_execution_relevant_link")
    # ### end Alembic commands ###
