"""Update artefact_matching_rule unique constraint

Revision ID: 3e09ecbeed0c
Revises: e9ada0b8b7a4
Create Date: 2026-02-26 15:59:55.781157+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e09ecbeed0c'
down_revision = 'e9ada0b8b7a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artefact_matching_rule_family_stage_track_branch_key', 'artefact_matching_rule', type_='unique')
    op.create_unique_constraint(op.f('artefact_matching_rule_family_stage_track_branch_key'), 'artefact_matching_rule', ['family', 'stage', 'track', 'branch'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artefact_matching_rule_family_stage_track_branch_key'), 'artefact_matching_rule', type_='unique')
    op.create_unique_constraint('artefact_matching_rule_family_stage_track_branch_key', 'artefact_matching_rule', ['family', 'stage', 'track', 'branch'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###
