
"""Make artefact-build many-to-many

Revision ID: 05880f3097cb
Revises: 717189ad8f3f
Create Date: 2026-04-29 17:17:13.861121+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05880f3097cb'
down_revision = '717189ad8f3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artefact_builds_association',
    sa.Column('artefact_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefact.id'], name=op.f('artefact_builds_association_artefact_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['build_id'], ['artefact_build.id'], name=op.f('artefact_builds_association_build_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artefact_id', 'build_id', name=op.f('artefact_builds_association_pkey'))
    )
    # ### end Alembic commands ###

    op.execute("""INSERT INTO artefact_builds_association (artefact_id, build_id) SELECT artefact_id, id FROM artefact_build WHERE artefact_id IS NOT NULL""")
    # op.drop_constraint("artefact_build_artefact_id_fkey", "artefact_build", type_="foreignkey")
    op.drop_column("artefact_build", "artefact_id", index=True)


def downgrade() -> None:
    op.add_column("artefact_build", sa.Column("artefact_id", sa.INTEGER(), nullable=True, index=True))
    op.create_foreign_key("artefact_build_artefact_id_fkey", "artefact_build", "artefact", ["artefact_id"], ["id"], ondelete="CASCADE")
    op.create_index("artefact_build_artefact_id_architecture_revision_ix", "artefact_build", ["artefact_id", "architecture", "revision"])
    op.execute("""UPDATE artefact_build
               SET artefact_id = aba.artefact_id
               FROM artefact_builds_association aba
               WHERE aba.build_id = artefact_build.id
               AND artefact_build.id NOT IN (
                   SELECT build_id FROM artefact_builds_association
                   GROUP BY build_id HAVING COUNT(*) > 1
               )
               """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artefact_builds_association')
    # ### end Alembic commands ###
