# Copyright 2026 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3, as
# published by the Free Software Foundation.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-FileCopyrightText: Copyright 2026 Canonical Ltd.
# SPDX-License-Identifier: AGPL-3.0-only

"""Add name field to AMRs

Revision ID: fa15d31d9a31
Revises: 983168a63271
Create Date: 2026-03-25 12:20:36.268377+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa15d31d9a31'
down_revision = '983168a63271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artefact_matching_rule', sa.Column('name', sa.String(length=200), server_default='', nullable=False))
    op.drop_constraint('artefact_matching_rule_family_stage_track_branch_key', 'artefact_matching_rule', type_='unique')
    op.create_unique_constraint(op.f('artefact_matching_rule_name_family_stage_track_branch_key'), 'artefact_matching_rule', ['name', 'family', 'stage', 'track', 'branch'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artefact_matching_rule_name_family_stage_track_branch_key'), 'artefact_matching_rule', type_='unique')
    op.create_unique_constraint('artefact_matching_rule_family_stage_track_branch_key', 'artefact_matching_rule', ['family', 'stage', 'track', 'branch'])
    op.drop_column('artefact_matching_rule', 'name')
    # ### end Alembic commands ###
