# Copyright 2026 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3, as
# published by the Free Software Foundation.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-FileCopyrightText: Copyright 2026 Canonical Ltd.
# SPDX-License-Identifier: AGPL-3.0-only

"""Create Release Manifests model

Revision ID: 0717f8d81ac1
Revises: daf0503863d7
Create Date: 2026-04-22 17:34:25.084538+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0717f8d81ac1"
down_revision = "daf0503863d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charm_manifest",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("charm_manifest_pkey")),
    )
    op.create_table(
        "release_manifest",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("track", sa.String(length=100), nullable=False),
        sa.Column("risk", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("release_manifest_pkey")),
    )
    op.create_table(
        "release_manifest_charm_manifest_association",
        sa.Column("release_manifest_id", sa.Integer(), nullable=False),
        sa.Column("charm_manifest_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["charm_manifest_id"],
            ["charm_manifest.id"],
            name=op.f("release_manifest_charm_manifest_association_charm_manifest_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["release_manifest_id"],
            ["release_manifest.id"],
            name=op.f("release_manifest_charm_manifest_association_release_manifest_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "release_manifest_id", "charm_manifest_id", name=op.f("release_manifest_charm_manifest_association_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_manifest_charm_manifest_association")
    op.drop_table("release_manifest")
    op.drop_table("charm_manifest")
    # ### end Alembic commands ###
