
"""Add all Artefact attributes to ArtefactMatchingRules

Revision ID: d9c144615947
Revises: f0847700d32e
Create Date: 2026-04-15 22:58:28.960881+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c144615947'
down_revision = 'f0847700d32e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artefact_matching_rule', sa.Column('store', sa.String(), server_default='', nullable=False))
    op.add_column('artefact_matching_rule', sa.Column('series', sa.String(), nullable=False))
    op.add_column('artefact_matching_rule', sa.Column('os', sa.String(length=200), nullable=False))
    op.add_column('artefact_matching_rule', sa.Column('release', sa.String(length=200), nullable=False))
    op.add_column('artefact_matching_rule', sa.Column('owner', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artefact_matching_rule', 'owner')
    op.drop_column('artefact_matching_rule', 'release')
    op.drop_column('artefact_matching_rule', 'os')
    op.drop_column('artefact_matching_rule', 'series')
    op.drop_column('artefact_matching_rule', 'store')
    # ### end Alembic commands ###
