"""add artefact matching rules

Revision ID: 40b42f906881
Revises: f5f3abf809b3
Create Date: 2026-02-27 12:46:27.207034+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '40b42f906881'
down_revision = 'f5f3abf809b3'
branch_labels = None
depends_on = None


family_type = postgresql.ENUM('snap', 'deb', 'charm', 'image', name='familyname', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artefact_matching_rule',
    sa.Column('family', family_type, nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('track', sa.String(length=200), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('artefact_matching_rule_pkey')),
    sa.UniqueConstraint('family', 'stage', 'track', 'branch', name=op.f('artefact_matching_rule_family_stage_track_branch_key'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('artefact_matching_rule_team_association',
    sa.Column('artefact_matching_rule_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artefact_matching_rule_id'], ['artefact_matching_rule.id'], name=op.f('artefact_matching_rule_team_association_artefact_matching_rule_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('artefact_matching_rule_team_association_team_id_fkey')),
    sa.PrimaryKeyConstraint('artefact_matching_rule_id', 'team_id', name=op.f('artefact_matching_rule_team_association_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artefact_matching_rule_team_association')
    op.drop_table('artefact_matching_rule')
    # ### end Alembic commands ###
