# Copyright (C) 2026 Canonical Ltd.
#
# This file is part of Test Observer Backend.
#
# Test Observer Backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3, as
# published by the Free Software Foundation.
#
# Test Observer Backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-FileCopyrightText: Copyright 2026 Canonical Ltd.
# SPDX-License-Identifier: AGPL-3.0-only

"""Add reviewers to ArtefactBuildEnvironmentReview

Revision ID: 2f7a130290ea
Revises: 3514f071a2e5
Create Date: 2026-02-27 16:21:41.550648+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7a130290ea'
down_revision = '3514f071a2e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_review_reviewers_association',
    sa.Column('environment_review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['environment_review_id'], ['artefact_build_environment_review.id'], name=op.f('environment_review_reviewers_association_environment_review_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('environment_review_reviewers_association_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('environment_review_id', 'user_id', name=op.f('environment_review_reviewers_association_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environment_review_reviewers_association')
    # ### end Alembic commands ###
