"""Add jira_epic attribute to artefacts

Revision ID: 148db3d7155d
Revises: 983168a63271
Create Date: 2026-03-25 14:44:17.378594+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "148db3d7155d"
down_revision = "983168a63271"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artefact", sa.Column("jira_epic", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artefact", "jira_epic")
    # ### end Alembic commands ###
