# Copyright 2026 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3, as
# published by the Free Software Foundation.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-FileCopyrightText: Copyright 2026 Canonical Ltd.
# SPDX-License-Identifier: AGPL-3.0-only

"""Add name field to AMRs

Revision ID: 7bef9e72e7b1
Revises: 983168a63271
Create Date: 2026-03-24 14:09:57.417457+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7bef9e72e7b1"
down_revision = "983168a63271"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artefact_matching_rule", sa.Column("name", sa.String(length=200), nullable=True))
    op.create_unique_constraint(op.f("artefact_matching_rule_name_key"), "artefact_matching_rule", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("artefact_matching_rule_name_key"), "artefact_matching_rule", type_="unique")
    op.drop_column("artefact_matching_rule", "name")
    # ### end Alembic commands ###
