# Copyright (C) 2023 Canonical Ltd.
#
# This file is part of Test Observer Backend.
#
# Test Observer Backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3, as
# published by the Free Software Foundation.
#
# Test Observer Backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add unique constraint to artefact_matching_rule

Revision ID: a3c0e9e00850
Revises: 24f85f32bbb8
Create Date: 2026-02-09 17:25:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c0e9e00850'
down_revision = '24f85f32bbb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f('artefact_matching_rule_family_stage_track_branch_key'),
        'artefact_matching_rule',
        ['family', 'stage', 'track', 'branch']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('artefact_matching_rule_family_stage_track_branch_key'),
        'artefact_matching_rule',
        type_='unique'
    )
    # ### end Alembic commands ###
