"""Add risk and builds hash to Artefact

Revision ID: 717189ad8f3f
Revises: daf0503863d7
Create Date: 2026-04-24 14:01:28.456621+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "717189ad8f3f"
down_revision = "ddde174f77d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artefact", sa.Column("risk", sa.String(length=200), nullable=False, server_default=""))
    # ### end Alembic commands ###
    op.add_column("artefact", sa.Column("builds_hash", sa.String(64), nullable=True))

    # Add unique constraint on (name, source, version, track, risk, builds_hash) for solution family
    op.create_index(
        "unique_solution",
        "artefact",
        ["name", "source", "version", "track", "risk", "builds_hash"],
        unique=True,
        postgresql_where=sa.text("family = 'solution'"),
    )

    # Create trigger function: sort build ids, merge them into a string and hash it
    op.execute("""
    CREATE OR REPLACE FUNCTION update_solution_builds_hash()
    RETURNS TRIGGER AS $$
    DECLARE
        builds_id_list TEXT;
    BEGIN
        -- Only for solution artefacts
        IF NEW.family = 'solution' THEN
            -- Get IDs sorted as integers, then merge into string
            SELECT STRING_AGG(id::TEXT, ',')
            INTO builds_id_list
            FROM (
                SELECT id FROM artefact_build
                WHERE artefact_id = NEW.id
                ORDER BY id ASC
            ) sorted_builds;
            
            -- Create hash of the sorted list
            NEW.builds_hash := MD5(COALESCE(builds_id_list, ''));
        ELSE
            NEW.builds_hash := NULL;
        END IF;
        
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    # On artefact insert/update, update builds hash
    op.execute("""
    CREATE OR REPLACE TRIGGER artefact_builds_hash_trigger
    BEFORE INSERT OR UPDATE ON artefact
    FOR EACH ROW
    EXECUTE FUNCTION update_solution_builds_hash();
    """)

    # On artefact_build insert/update/delete, trigger update of artefact to recalculate hash
    op.execute("""
    CREATE OR REPLACE FUNCTION update_parent_artefact_hash()
    RETURNS TRIGGER AS $$
    BEGIN
        -- Get the parent artefact and trigger its update to recalculate hash
        UPDATE artefact SET updated_at = NOW() WHERE id = COALESCE(NEW.artefact_id, OLD.artefact_id);
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE OR REPLACE TRIGGER artefact_build_hash_update_trigger
    AFTER INSERT OR UPDATE OR DELETE ON artefact_build
    FOR EACH ROW
    EXECUTE FUNCTION update_parent_artefact_hash();
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artefact", "risk")
    # ### end Alembic commands ###

    # triggers
    op.execute("DROP TRIGGER IF EXISTS artefact_build_hash_update_trigger ON artefact_build")
    op.execute("DROP FUNCTION IF EXISTS update_parent_artefact_hash()")
    op.execute("DROP TRIGGER IF EXISTS artefact_builds_hash_trigger ON artefact")
    op.execute("DROP FUNCTION IF EXISTS update_solution_builds_hash()")
    op.execute("DROP INDEX IF EXISTS unique_solution")
    op.drop_column("artefact", "builds_hash")
