
"""Add notifications

Revision ID: 983168a63271
Revises: a1b2c3d4e5f6
Create Date: 2026-03-10 16:18:40.152277+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '983168a63271'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('USER_ASSIGNED_ARTEFACT_REVIEW', 'USER_ASSIGNED_ENVIRONMENT_REVIEW', name='notificationtype'), nullable=False),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('notification_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    op.create_index(op.f('notification_user_id_ix'), 'notification', ['user_id'], unique=False)
    op.drop_table('artefact_matching_rule_team_association')
    op.drop_table('artefact_matching_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artefact_matching_rule',
    sa.Column('family', postgresql.ENUM('snap', 'deb', 'charm', 'image', name='familyname'), autoincrement=False, nullable=False),
    sa.Column('stage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('track', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('artefact_matching_rule_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='artefact_matching_rule_pkey'),
    sa.UniqueConstraint('family', 'stage', 'track', 'branch', name='artefact_matching_rule_family_stage_track_branch_key', postgresql_nulls_not_distinct=True),
    postgresql_ignore_search_path=False
    )
    op.create_table('artefact_matching_rule_team_association',
    sa.Column('artefact_matching_rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artefact_matching_rule_id'], ['artefact_matching_rule.id'], name='artefact_matching_rule_team_association_artefact_matchi_be42'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='artefact_matching_rule_team_association_team_id_fkey'),
    sa.PrimaryKeyConstraint('artefact_matching_rule_id', 'team_id', name='artefact_matching_rule_team_association_pkey')
    )
    op.drop_index(op.f('notification_user_id_ix'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
