"""Add risk and builds hash to Artefact

Revision ID: 717189ad8f3f
Revises: daf0503863d7
Create Date: 2026-04-24 14:01:28.456621+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "717189ad8f3f"
down_revision = "ddde174f77d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artefact_bundled_builds_association',
    sa.Column('artefact_id', sa.Integer(), nullable=False),
    sa.Column('artefact_build_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artefact_build_id'], ['artefact_build.id'], name=op.f('artefact_bundled_builds_association_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefact.id'], name=op.f('artefact_bundled_builds_artefact_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artefact_id', 'artefact_build_id', name=op.f('artefact_bundled_builds_association_pkey'))
    )

    op.add_column("artefact", sa.Column("risk", sa.String(length=200), nullable=False, server_default=""))
    # ### end Alembic commands ###
    op.add_column("artefact", sa.Column("bundled_builds_hash", sa.String(64), nullable=True))

    # Add unique constraint on (name, source, version, track, risk, bundled_builds_hash) for solution family
    op.create_index(
        "unique_solution",
        "artefact",
        ["name", "source", "version", "track", "risk", "bundled_builds_hash"],
        unique=True,
        postgresql_where=sa.text("family = 'solution'"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artefact", "risk")
    op.drop_table('artefact_bundled_builds_association')
    # ### end Alembic commands ###
    op.drop_column("artefact", "bundled_builds_hash")
