# Copyright (C) 2023 Canonical Ltd.
#
# This file is part of Test Observer Backend.
#
# Test Observer Backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3, as
# published by the Free Software Foundation.
#
# Test Observer Backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add ArtefactMatchingRule model and team association

Revision ID: 24f85f32bbb8
Revises: a1035f9064d2
Create Date: 2026-02-09 17:02:34.554368+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '24f85f32bbb8'
down_revision = 'f5f3abf809b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing familyname enum type
    familyname_enum = postgresql.ENUM('snap', 'deb', 'charm', 'image', name='familyname', create_type=False)
    
    op.create_table('artefact_matching_rule',
    sa.Column('family', familyname_enum, nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('track', sa.String(length=200), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('artefact_matching_rule_pkey')),
    sa.UniqueConstraint('family', 'stage', 'track', 'branch', 
                        name=op.f('artefact_matching_rule_family_stage_track_branch_key'),
                        postgresql_nulls_not_distinct=True)
    )
    op.create_table('artefact_matching_rule_team_association',
    sa.Column('artefact_matching_rule_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artefact_matching_rule_id'], ['artefact_matching_rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id']),
    sa.PrimaryKeyConstraint('artefact_matching_rule_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artefact_matching_rule_team_association')
    op.drop_table('artefact_matching_rule')
    # ### end Alembic commands ###
