"""Add reviewer_families to team and fix foreign key

Revision ID: a9bbde44e3d5
Revises: 24f85f32bbb8
Create Date: 2026-02-26 16:06:45.954787+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9bbde44e3d5'
down_revision = '24f85f32bbb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artefact_matching_rule_team_association_artefact_matchi_be42', 'artefact_matching_rule_team_association', type_='foreignkey')
    op.create_foreign_key(op.f('artefact_matching_rule_team_association_artefact_matching_rule_id_fkey'), 'artefact_matching_rule_team_association', 'artefact_matching_rule', ['artefact_matching_rule_id'], ['id'])
    op.add_column('team', sa.Column('reviewer_families', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'reviewer_families')
    op.drop_constraint(op.f('artefact_matching_rule_team_association_artefact_matching_rule_id_fkey'), 'artefact_matching_rule_team_association', type_='foreignkey')
    op.create_foreign_key('artefact_matching_rule_team_association_artefact_matchi_be42', 'artefact_matching_rule_team_association', 'artefact_matching_rule', ['artefact_matching_rule_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
