
"""Add name field to AMRs

Revision ID: 74248fa0f5cf
Revises: 983168a63271
Create Date: 2026-03-24 13:17:37.785574+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74248fa0f5cf'
down_revision = '983168a63271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artefact_matching_rule', sa.Column('name', sa.String(length=200), nullable=False))
    op.create_unique_constraint(op.f('artefact_matching_rule_name_key'), 'artefact_matching_rule', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artefact_matching_rule_name_key'), 'artefact_matching_rule', type_='unique')
    op.drop_column('artefact_matching_rule', 'name')
    # ### end Alembic commands ###
