# SPDX-FileCopyrightText: Copyright 2026 Canonical Ltd.
# SPDX-License-Identifier: GPL-3.0-only

"""Add permissions to AMRs

Revision ID: c29b4f545a9b
Revises: 983168a63271
Create Date: 2026-03-23 17:33:11.270550+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c29b4f545a9b'
down_revision = '983168a63271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    permission_enum = postgresql.ENUM(
        'view_user', 'change_user', 'view_team', 'change_team', 
        'add_application', 'change_application', 'view_application', 'view_permission', 
        'view_issue', 'change_issue', 'change_issue_attachment', 'change_issue_attachment_bulk', 
        'change_attachment_rule', 'change_auto_rerun', 'view_test', 'change_test', 
        'view_rerun', 'change_rerun', 'change_rerun_bulk', 'view_artefact', 
        'change_artefact', 'view_environment_review', 'change_environment_review', 
        'view_report', 'view_test_case_reported_issue', 'change_test_case_reported_issue', 
        'view_environment_reported_issue', 'change_environment_reported_issue', 
        name='permission'
    )
    permission_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('artefact_matching_rule', sa.Column('grant_permissions', postgresql.ARRAY(permission_enum), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artefact_matching_rule', 'grant_permissions')
    permission_enum = postgresql.ENUM(name='permission')
    permission_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
