
"""Add risk to Artefact

Revision ID: 717189ad8f3f
Revises: daf0503863d7
Create Date: 2026-04-24 14:01:28.456621+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717189ad8f3f'
down_revision = 'daf0503863d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artefact', sa.Column('risk', sa.String(length=200), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artefact', 'risk')
    # ### end Alembic commands ###
