
"""Add bundled builds association between artefact and build

Revision ID: 3840b18f5bee
Revises: 717189ad8f3f
Create Date: 2026-05-05 10:50:16.196333+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3840b18f5bee'
down_revision = '717189ad8f3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artefact_build_bundle_solution',
    sa.Column('artefact_id', sa.Integer(), nullable=False),
    sa.Column('artefact_build_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artefact_build_id'], ['artefact_build.id'], name=op.f('artefact_build_bundle_solution_artefact_build_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefact.id'], name=op.f('artefact_build_bundle_solution_artefact_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artefact_id', 'artefact_build_id', name=op.f('artefact_build_bundle_solution_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artefact_build_bundle_solution')
    # ### end Alembic commands ###
