name: Run charm tests
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  
jobs:
  publish-charm:
    name: Publish Charm
    needs: integration-test
    runs-on: [self-hosted, linux]
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Fetch Tested Charm
        uses: actions/download-artifact@v3
        with:
          name: tested-charm
      - name: Move charm in current directory
        run: find ./ -name test-observer-frontend_ubuntu-22.04-amd64.charm -exec mv -t ./ {} \;
      - name: Select Charmhub channel
        uses: canonical/charming-actions/channel@2.2.2
        id: channel
      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.2.2
        with:
          credentials: "${{ secrets.CHARMHUB_AUTH_API }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
