on:
  push:
    branches:
      - master
  
jobs:
  build:
    name: Release test-observer-frontend charm to latest/edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.2.0
        with:
          charm-path: "frontend/charm"
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  