name: Static Analysis - Backend Charm

on:
  pull_request:
    paths:
      - 'backend/charm/**'
      - '.github/workflows/static-analysis-backend-charm.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze-backend-charm:
    name: Analyze Backend Charm
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend/charm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.10"
      - run: pip install uv
      - run: uv sync --all-groups
      - run: uv pip install -e .
      - if: ${{ !cancelled() }}
        run: uv run ruff check
      - if: ${{ !cancelled() }}
        run: uv run ruff format --check
      - if: ${{ !cancelled() }}
        run: uv run mypy .